# Generated by Django 4.2.3 on 2023-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user_id', models.CharField()),
                ('telegram_user_id', models.CharField(unique=True)),
            ],
        ),
    ]
