# Generated by Django 4.2.3 on 2023-07-22 16:03

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('phone_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5,15}$', 'Enter a valid phone number. Min lenght is 5, max lenght is 15, only numbers.')]), size=None)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), size=None)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=None)),
                ('updated_at', models.DateTimeField(blank=True, default=None)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('status', models.CharField(choices=[('family', 'family'), ('friend', 'friend'), ('partner', 'partner'), ('colleague', 'colleague'), ('other', 'other')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
