# Generated by Django 4.2.1 on 2023-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="sex",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
