# Generated by Django 4.2.1 on 2023-07-24 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactsapp", "0002_alter_contact_sex_alter_contact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{5,15}$",
                        "Enter a valid phone number. Min lenght is 5, max lenght is 15, only numbers.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sex",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
