# Generated by Django 4.2.1 on 2023-07-24 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactsapp", "0003_alter_contact_address_alter_contact_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4,20}$", "only numbers, 4-20 digit"
                    )
                ],
            ),
        ),
    ]
