# Generated by Django 4.2.1 on 2023-07-24 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactsapp", "0004_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4,20}$", "only numbers, 4-20 digit"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sex",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(),
        ),
    ]
